### ISSUE TITLE
How to replace mockFs in mocha

### ISSUE THREAD

**Issue by dicolasi** [streamich/memfs#1025]
Hi all,
I am in the process of replacing mock-fs with mem-fs due to its lack of support for node 20.X. I am struggling to get mem-fs working in this simple case:

Here the original test case with mock-fs:

```
  it('should use local hosts if they exist', async () => {
    mockFs({
      'admin/exchange-hosts.yaml': mockFs.load('test/unit/input-files/exchange-hosts.yaml'),
      'exchange-config': mockFs.load('test/unit/input-files/gateway/exchange-config-integration')
    });
    await validateHostsByEnvironment({ exchangeConfigPath: 'exchange-config', env: Environment.production, validation });
    expect(validation.errors).to.be.empty;
    expect(validation.warnings).to.be.empty;
    expect(validation.info).to.contain('[prod/real.yaml] Hosts authorised');
    expect(getExchangeHostsRawStub.notCalled).to.be.true;
  });
```
and here the refactored one with mem-fs that does not work:

```
  it('should use local hosts if they exist', async () => {
    vol.fromNestedJSON({
      'admin/exchange-hosts.yaml': ufs.readFileSync('test/unit/input-files/exchange-hosts.yaml'),
      'exchange-config': await loadIntoMockFS('test/unit/input-files/gateway/exchange-config-integration'),
    }, appPath);
    await validateHostsByEnvironment({ exchangeConfigPath: 'exchange-config', env: Environment.production, validation });
    expect(validation.errors).to.be.empty;
    expect(validation.warnings).to.be.empty;
    expect(validation.info).to.contain('[prod/real.yaml] Hosts authorised');
    expect(getExchangeHostsRawStub.notCalled).to.be.true;
  });
```
the method loadIntoMockFS is here:

```
async function loadIntoMockFS(dirPath: string): Promise<NestedDirectoryJSON> {
  const entries = await fsPromises.readdir(dirPath, {withFileTypes: true});
  const fileTree: NestedDirectoryJSON = {};

  for (const entry of entries) {
    const entryPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      fileTree[entry.name] = await loadIntoMockFS(entryPath);
    } else if (entry.isFile()) {
      fileTree[entry.name] = await fsPromises.readFile(entryPath, 'utf-8');
    }
  }

  return fileTree;
}
```
I am not sure I actually need the loadIntoMockFS method at all. The test fail since it cannot find the folde exchange-config cannot be found (but if I print vol.tree I can definitely see it).

I am sure I am missing something stupid here :) For instance, I would need to stub the `fs`, `fs-extra` in the src code, but I do not know an elegant way to achieve that using sinon. 

Can anyone please help?

**Comment by G-Rath** [comment]
It sounds like you might already know this but you've not explicitly mentioned it and it's important: `mockfs` implicitly replaces the native `fs` module where `memfs` just provides an in-memory implementation of the native module.

That means as your example is written, your memory FS does nothing and your src code uses the actual file system which is why it errors.

You should look into how to do native module mocking with `sinon`: https://sinonjs.org/how-to/link-seams-commonjs/

https://github.com/G-Rath/audit-app is a real world app using jest which mocks FS in tests with a memory FS, that could also be useful for you
