### ISSUE TITLE
Dirent.#path changed when upgrading from 4.8.0 to 4.9.2 ::  it doesn't include the last segment 

### ISSUE THREAD

**Issue by marcog83** [streamich/memfs#1033]
Hi Streammich. 
We use memfs in our project to manage virtual file-system, and it fit 100% our needs. You saved a lot of headaches :) to our team. 

I have this `ViewsManager` Class with `getView` method as below

```ts
export class ViewsManager {
  #fs: IFs;

  #volume: Volume = new Volume();

  constructor() {
    this.#fs = createFsFromVolume(this.#volume);
  }

  setViews(views: View[]) {
    const tree = createTree(views);
    this.#volume.fromJSON(tree, '/');
  }
  getViews() {
    const contents = (this.#fs.readdirSync('/', { recursive: true, withFileTypes: true }) ?? []) as Dirent[];
    return contents
      .filter((item) => item.isFile())
      .map((item) => {
        const file = this.#fs.readFileSync(item.path, 'utf8') ?? '';
        const content: View = JSON.parse(file.toString());
        content.path = item.path;
        return content;
      }).sort((a, b) => a.label.localeCompare(b.label, undefined, {
        sensitivity: 'base',
        caseFirst: 'upper',
        numeric: true,
      })) as View[];
  }
 //...
```
Then i have a jest test like this. internally `createTree(views)` reduces the array to
```js
{
      '/my-root-saved-view': '{"path":"/my-root-saved-view","id":"0","data":"Data: 0","label":"Label: 0","updatedAt":0}',
      '/folder/nested/my-nested-saved-view': '{"path":"/folder/nested/my-nested-saved-view","id":"1","data":"Data: 1","label":"Label: 1","updatedAt":0}',
      '/folder/nested/2nd-nested-saved-view': '{"path":"/folder/nested/2nd-nested-saved-view","id":"2","data":"Data: 2","label":"Label: 2","updatedAt":0}'
    }
```
<img width="558" alt="image" src="https://github.com/streamich/memfs/assets/4071265/8eaa8fc9-2e71-4c9c-a039-41c35058e0f7">

When i run the test with memfs 4.8.0 it works as expected, but if i use latest version 4.9.2 i get this error. 

<img width="917" alt="image" src="https://github.com/streamich/memfs/assets/4071265/f0d22c20-09d8-4aa9-aadd-7f11a4f68d23">

After logging the `item` i see this difference. 
it seems
4.8.1 includes the entire path in `path` field
4.9.2 doesn't include the last segment
![image](https://github.com/streamich/memfs/assets/4071265/d68fbe8c-dfa7-4e1c-80bd-34eb583f3c63)

is it expected?

**Comment by streamich** [comment]
You are probably affected by this bug fix: https://github.com/streamich/memfs/pull/1024

**Comment by marcog83** [comment]
Thanks for the replay. I' LL update my code to join parh+name then. I wanted to confirm that i was doing the right thing, and not Just something that happened to work 😀
