### ISSUE TITLE
Can I use IndexedDB as a storage?

### ISSUE THREAD

**Issue by lesomnus** [streamich/memfs#1053]
I want to write a file that is stored in the browser. Since the file is to be uploaded to the server, it does not need to be saved in the host. Also the file will be quite large (~20GB) so I want to use IndexedDB to store the file.

**Comment by G-Rath** [comment]
No, `memfs` is designed for storing in-memory, hence the name - there are a number of ways that you could use IndexedDB to back a file system such as https://dexie.org/ or https://www.npmjs.com/package/idb
