### ISSUE TITLE
Specifying directories in .fromJSON()?

### ISSUE THREAD

**Issue by ianwalter** [streamich/memfs#106]
How do you feel about being able to specify directories in `.fromJSON()`? It might look like:
```js
const vol = Volume.fromJSON({
  '/foo': {}
})
```
I think this would be a little easier than using `mkdirp` when you have multiple directories that need to be created.

**Comment by streamich** [comment]
I like the idea. Also see: 

- https://github.com/streamich/memfs/issues/48
- https://github.com/streamich/memfs/issues/29

**Comment by streamich** [comment]
See this: https://github.com/streamich/memfs/pull/107
