### ISSUE TITLE
Watch directory for new files

### ISSUE THREAD

**Issue by jacobalberty** [streamich/memfs#116]
the memfs.watch() function doesn't seem to work on directories. The following code works as expected:
```
var fs = require('fs');
if (fs.vol) fs.vol.fromJSON({ '/tmp': {}});
var fswatcher = fs.watch('/tmp', console.log);
fs.writeFileSync('/tmp/test.file', 'test data');
fs.unlinkSync('/tmp/test.file');
setTimeout(() => {fswatcher.close()}, 500);
```
Producing the output:
```
rename test.file
change test.file
rename test.file
```

but change it to use memfs instead::
```
var fs = require('memfs');
if (fs.vol) fs.vol.fromJSON({ '/tmp': {}});
var fswatcher = fs.watch('/tmp', console.log);
fs.writeFileSync('/tmp/test.file', 'test data');
fs.unlinkSync('/tmp/test.file');
setTimeout(() => {fswatcher.close()}, 500);
```
and I get no output.

EDIT: Changed the test code to be a little simpler and make the two cases much closer to each other with only a single line change.

**Comment by williamstein** [comment]
I just noticed that memfs doesn't properly update directory timestamps (as it should according to POSIX) when files are added/removed in a directory.  This is probably related to your problem.  I'll at least make an issue about this.

**Comment by williamstein** [comment]
I don't think my #869 is relevant.  However, I just tried your example with the current version of memfs (from this repo at least) and it worked fine for me, and did show output.  Maybe this bug is fixed?

**Comment by streamich** [comment]
Closing as per https://github.com/streamich/memfs/issues/116#issuecomment-1291524871 it might be fixed. Please re-open, if not.
