### ISSUE TITLE
fs functions missing

### ISSUE THREAD

**Issue by masaeedu** [streamich/memfs#122]
Hi there. The `README.md` says 100% of Node's `fs` API is implemented, but I can't find `copy` or `copyFile` in the [API status](https://github.com/streamich/memfs/blob/master/docs/api-status.md) markdown file or in the object I'm getting at runtime. Is this a bug?

**Comment by streamich** [comment]
Hi there. `copyFile` was added in Node 8.5, which was after this lib was written. But, yes, you are right, it is a bug and should be implemented.

**Comment by streamich** [comment]
I've added both methods to the list:

- https://github.com/streamich/memfs/blob/master/docs/api-status.md

[Copy file constant and implementation](https://github.com/nodejs/node/blob/master/lib/fs.js#L1919).

**Comment by streamich** [comment]
Should be implemented now.
