### ISSUE TITLE
Which version is latest stable?

### ISSUE THREAD

**Issue by aleung** [streamich/memfs#123]
On github project release page, latest is `2.6.2`. The `package.json` on master branch is `2.7.2`. While I run `npm install memfs` I got `2.8.0`.

**Comment by streamich** [comment]
Release page is not up-to-date, as `semantic-release` stopped working, the latest version is `2.8.0`.

We added an ability to specify empty dir as `{}` here: https://github.com/streamich/memfs/issues/106

**Comment by aleung** [comment]
Thanks. I see.
