### ISSUE TITLE
Path to `fs-monkey`

### ISSUE THREAD

**Issue by isaackwan** [streamich/memfs#146]
Hi! Thanks for the great work!

Currently it doesn't build (click [here](https://circleci.com/gh/cloudy-db/js/19) for an example) unless I change the references from `fs-monkey/lib/<blah>` to `fs-monkey/src/<blah>`. (Click [me](https://github.com/cloudy-db/memfs/commit/bd825be5646cedbae3d86dc5fbf7b3fd9ef838e8)) to see what I mean.

**Comment by isaackwan** [comment]
OK, I guess the thing is that `fs-monkey` did not ship with compiled outputs in `lib` for some reason?

**Comment by streamich** [comment]
Try `2.9.0`
