### ISSUE TITLE
Persistent/cached volumes

### ISSUE THREAD

**Issue by ev1stensberg** [streamich/memfs#163]
Hi! This is a question, close at any time if this is not the right platform. Is there any way to keep the `memfs` instance of a file/volume alive on a process that is closed and then opened again? 

An example would be to write a "Mocked" file on first run, and when the process runs the next time, the file is available.

**Comment by ev1stensberg** [comment]
Importing back would be done in memory? ( Just do be sure ) Thanks for the help!

**Comment by streamich** [comment]
You would need to persist that JSON somewhere and load it next time your process runs.

**Comment by ev1stensberg** [comment]
So no way of doing that without actually having to do a physical write?

**Comment by ev1stensberg** [comment]
okay, gotcha. Thanks for elaboration @streamich ! ❤️
