### ISSUE TITLE
Node.js 6: `self.destroy` is not a function on `FsReadStream.prototype.open` error

### ISSUE THREAD

**Issue by deepsweet** [streamich/memfs#167]
Hi.

https://travis-ci.org/deepsweet/copie/jobs/396571967

Works fine with Node 8 and 10.

**Comment by streamich** [comment]
Because `Readable.prototype.destroy` was added in Node 8.

https://nodejs.org/api/stream.html#stream_readable_destroy_error

**Comment by deepsweet** [comment]
Got it, thanks.

So are you going to fix this by checking that `destroy` is a function?

**Comment by streamich** [comment]
Nope

**Comment by deepsweet** [comment]
Hm, ok :)

Then I wonder how does [Travis pass tests on Node 6](https://github.com/streamich/memfs/blob/a594e2b4f77eb7bcb733fe0e00d3f9c2ac901907/.travis.yml#L14) – lack of tests for `destroy()`?

And what's the lowest officially supported Node version? I can monkey patch that `destroy()` in stream object in one of my tests, but I can't drop entire the Node 6 for now.

**Comment by streamich** [comment]
OK, I don't know if that it a good idea, but I added a bunch of checks for you, see https://github.com/streamich/memfs/pull/168

Tell me what you think.

> Then I wonder how does Travis pass tests on Node 6 – lack of tests for destroy()?

The stream functionality is almost verbatim copy from Node 8; and, yes, it is not much tested here; but it is almost verbatim copy.

> And what's the lowest officially supported Node version?

The goal has always been to support the latest functionality, for example, a month ago I was working on adding new Node 10 error messages and `fs.promises` API.

With regards to backwards compatibility, there is no official stance. What would you suggest? Node 8 sounds reasonably as it is currenty "active" Node version, I myself use it a lot. Node 6 sounds a bit oldish, haven't used it for over a year.

**Comment by deepsweet** [comment]
>Tell me what you think

Thanks for the fix. I'm going to drop Node 6 in October when Node 10 will become an active LTS. I'm not using 6 by myself as well, but from what I see all the major modules still do support it.

>The stream functionality is almost verbatim copy from Node 8

I see, and I remember the story with different streams implementations across the Node versions.

>The goal has always been to support the latest functionality
>Node 8 sounds reasonably as it is currenty "active" Node version

I personally more agree than disagree with this, just want to be in sync with the lowest version supported by "community".

Feel free to reject that patch if you really don't like it :) But please mention the situation somewhere in readme, just to to avoid any confusion because I personally was expecting a real "drop-in replacement" looking just at Travis Node.js matrix.

**Comment by streamich** [comment]
Was released in `2.9.1`.
