### ISSUE TITLE
Publish TypeScript declaration files

### ISSUE THREAD

**Issue by ajafff** [streamich/memfs#213]
Currently the published package doesn't contain any `.d.ts` files although this library is written in TypeScript.
It would help a ton if declaration files were available as it's way easier to use within other TypeScript projects.

I don't quite understand why the build process needs gulp, typescript and babel. Wouldn't TypeScript suffice to compile all `src/**/*.ts` files to `lib` and also emit declaration files?

**Comment by streamich** [comment]
Yes, `tsc` should be enough.
