### ISSUE TITLE
Doesn’t work with relative paths

### ISSUE THREAD

**Issue by sapegin** [streamich/memfs#23]
After updating to 2.x relative paths don’t work:

```
> const { fs } = require('memfs');
undefined
> fs.writeFileSync('f', 't');
TypeError: Cannot read property 'createChild' of null
    at Volume.createLink (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:423:22)
    at Volume.openFile (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:690:29)
    at Volume.openBase (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:698:25)
    at Volume.writeFileBase (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:927:23)
    at Volume.writeFileSync (/Users/sapegin/Dropbox/Projects/_Repos/mrm-core/node_modules/memfs/lib/volume.js:952:14)
    at repl:1:4
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
> fs.writeFileSync('/f', 't');
undefined
```

**Comment by sapegin** [comment]
Trying to debug the issue: it tries to resolve the file path using my current working directory with is obviously doesn’t exist in memfs volume:

```
> const { fs } = require('memfs');
undefined
> process.cwd()
'/Users/sapegin/Dropbox/Projects/_Repos/mrm-core'
> process.chdir('/');
undefined
> fs.writeFileSync('f', 't');
undefined
```

**Comment by streamich** [comment]
How do you expect it to work with relative paths?

**Comment by sapegin** [comment]
It used to work in 0.x so I’m not sure what has changed. It’s either a regression or should be documented that `process.chdir('/');` is required to work with relative paths.

**Comment by streamich** [comment]
> It used to work in 0.x 

How can I reproduce it? Because if I install version `0.0.15` and try to `writeFileSync('f', 't')` it also throws an error, because it also depends on current working directory.

>  I’m not sure what has changed

The version `2.x` is a complete rewrite, with support for `Buffer`, symlinks, hardlinks etc.

> should be documented that process.chdir('/'); is required to work with relative paths

That's a good idea. Also I'm not sure how to approach the current working path, yet. Is it a good idea to use it at all? Because that is tied to the actual on-disk filesystem.

Now, one way to go is you can try to create a directory at the current path, before doing any operations, something like this:

```js
import {mkdirpSync} from 'memfs';

mkdirpSync(process.cwd());
```

**Comment by sapegin** [comment]
> How can I reproduce it? Because if I install version 0.0.15 and try to writeFileSync('f', 't') it also throws an error, because it also depends on current working directory.

I found the reason. I used to do this:

```js
const memfs = require('memfs');
const fs = new memfs.Volume();
fs.mountSync('./', {});
module.exports = fs;
```

And now I do this:

```js
const { createFsFromVolume, Volume } = require('memfs');
const volume = Volume.fromJSON({});
module.exports = createFsFromVolume(volume);
```

So if I change it this way it would work fine:

```diff
const { createFsFromVolume, Volume } = require('memfs');
- const volume = Volume.fromJSON({});
+ const volume = Volume.fromJSON({}, '/');
module.exports = createFsFromVolume(volume);
```

> That's a good idea. Also I'm not sure how to approach the current working path, yet. Is it a good idea to use it at all? Because that is tied to the actual on-disk filesystem.

I think it works fine now. At least now, when I understand how it works, I think we shouldn’t change it.

But we can improve the experience:

1. Make it more clear from the docs and explain how to work with relative paths.
2. Make the error message more clear, now it’s impossible to guess what’s wrong with your code and how to fix that. Something like “Cannot write to /full/path/to/folder, directory doesn’t exist” would make debugging much easier.

**Comment by streamich** [comment]
> Make the error message more clear, now it’s impossible to guess what’s wrong with your code and how to fix that. Something like “Cannot write to /full/path/to/folder, directory doesn’t exist” would make debugging much easier.

The error message is indeed incorrect, it should throw the same error as Node.js, I'll fix that.

**Comment by sapegin** [comment]
The Node error doesn’t show absolute path which may save a lot of time debugging ;-)

**Comment by streamich** [comment]
Hmm, I want error message to be just like in Node, but Node doesn't indeed show the absolute path, although it is easy to do so. What do you think?

**Comment by streamich** [comment]
Made it throw `ENOENT` in #26 and added to readme:

https://github.com/streamich/memfs#relative-paths

**Comment by sapegin** [comment]
Awesome, thanks!
