### ISSUE TITLE
Using createReadStream fails

### ISSUE THREAD

**Issue by sbreiler** [streamich/memfs#272]
I'm trying to get a ftp server running with memfs (using: https://github.com/nodeftpd/nodeftpd).

nodeftpd at some point tries to read from fs:
`var rs = self.fs.createReadStream(null, {fd: fd});`
which fails by memfs with: 

> TypeError: path must be a string or Buffer
>    at pathToFilename (C:\projects\ftpproxy\node_modules\memfs\lib\volume.js:292:19)
>    at class_1.FsReadStream (C:\projects\ftpproxy\node_modules\memfs\lib\volume.js:1844:17)
>    at new class_1 (C:\projects\ftpproxy\node_modules\memfs\lib\volume.js:462:31)
>    at Volume.createReadStream (C:\projects\ftpproxy\node_modules\memfs\lib\volume.js:1739:16)
>    ...

Any suggestions on how to solve this? I think the null-Argument at createReadStream freaks memfs out :-D

**Comment by streamich** [comment]
It must be this line:

https://github.com/streamich/memfs/blob/master/src/volume.ts#L2180

And the current implementation in Node is like this:

https://github.com/nodejs/node/blob/master/lib/internal/fs/streams.js#L55

https://github.com/nodejs/node/blob/master/lib/internal/url.js#L1365
