### ISSUE TITLE
fs.readFile reads wrong file after renaming parent dir

### ISSUE THREAD

**Issue by Nishkalkashyap** [streamich/memfs#282]
## Steps to reproduce : 

1. fs.mkdirSync('/dir');

2. fs.writeFileSync('/dir/file.ext');

3. fs.readFileSync('/dir/file.ext'); 
 `//returns Buffer[]`

4. fs.renameSync('/dir/file.ext', '/dir/newfile.ext');

5. fx.readFileSync('/dir/newfile.ext'); 
`// Throws Error`

`Error: ENOENT: no such file or directory, open '/dir/file.ext'`

Even though new file name is entered in readFileSync, it still tries to look for the old file?

**Comment by streamich** [comment]
If in step 5 you rename `fx` to `fs`, does it work?

**Comment by falkenhawk** [comment]
@streamich try this reproduction, please: 🙏

```javascript
const fs = require('memfs');

fs.mkdirSync('dir', { recursive: true });
fs.writeFileSync('dir/file.ext', 'asdf');

fs.renameSync('dir', 'newdir');
fs.readFileSync('newdir/file.ext', 'utf8');
```

Still tries to read from the old path:
```
Error: ENOENT: no such file or directory, open '/(...)/dir/file.ext'
```

Note: it works just fine with `const fs = require('fs');`

**Comment by falkenhawk** [comment]
Also note: `statSync('newdir/file.ext')`, `accessSync`, `existsSync` all work fine after rename!
But `vol.toJSON()` still lists the file under the "old" path:
`{ '/(...)/dir/file.ext': 'asdf' }`

**Comment by G-Rath** [comment]
@falkenhawk your reproduction works fine for me using the latest version of `memfs` so I'm going to close this as hopefully its been fixed - feel free to open a new issue if you have any further problems.
