### ISSUE TITLE
Documenting use cases and best practices in one place

### ISSUE THREAD

**Issue by ChrisCinelli** [streamich/memfs#292]
I am a little confused on how and when to use `memfs`, `unionfs`, `linkfs`, `patchFs`, `patchRequire`, `jest-plugin-fs` etc. 

There are a lot of pieces to make a great vehicle but the instructions on how assembling them together are not well organized.  A lot of documentation is sparse across different repos and issues on those repos. Outdated info in old issues and changes in the state of the art make the matter even more complicated.

I suggest adding  a "Use cases" or "How to" section in the `README.md`.

Some points that I suggest to cover: 

- Using `memfs` with `jest`. It seems that `jest-plugin-fs` is a quick drop-in replacement
- Using `memfs` with `mocha`.
- Replace tests on a filesystem with `memfs`. I am working on an old repo that creates a tree from fixtures in a `./tmp` folder to run tests. I tried a few combinations of  `unionfs`, `linkfs`, `patchFs`, etc. and I still have not been able to make it work as I want.

Adding a reference to these use cases in other repos would also help people to find them.

**Comment by streamich** [comment]
For testing with Jest, you can check out `mrm-core`, here they mock the file system:

- https://github.com/sapegin/mrm-core/blob/master/__mocks__/fs.js

And here you can see `memfs` volume is reset after each test:

- https://github.com/sapegin/mrm-core/blob/master/src/__tests__/fs.spec.js#L22

**Comment by ChrisCinelli** [comment]
If you start with scratch with jest, everything seemed pretty straightforward. Now what is the difference between creating the `fs`'`__mock__` like in `mrm` and `jest-plugin-fs`.

Being able to use `memfs` with legacy code is less straightforward. See https://github.com/streamich/fs-monkey/issues/139. For example how would you do it in  https://github.com/75lb/renamer/tree/master/test ?

I was pointing out that with more cohesive documentation and examples people will have less friction in adopting `memfs`.

**Comment by mikeerickson** [comment]
@ChrisCinelli I am assuming you are only using `jest` but I am curious if you could shed some light on how it might be used with `mocha`.  I have a pretty full test suite (some 300+ tests) which are using `mocha`, thus moving to `jest` will be quite time consuming.
