### ISSUE TITLE
Is it possible to virualize only specific directory

### ISSUE THREAD

**Issue by purepear** [streamich/memfs#351]
I'm using Jest and fs-extra :)

I want to be able to mock certain absolute directory/directories with memfs... and leave everything else to the default "fs" module

Is this possible at all? (This means writing and reading files)

I saw `unionfs` but from the examples given(only reading files)... i'm not sure how to accomplish this with writing files as well.

**Comment by alexandrsek** [comment]
Hi! I encountered the same problem, were you able to solve it?

**Comment by purepear** [comment]
Hi @alexandrsek. Sorry, this was an old project and unfortunately i can't really remember.

**Comment by alexandrsek** [comment]
Sad, thank you for your reply and good luck

**Comment by G-Rath** [comment]
[`unionfs`](https://github.com/streamich/unionfs#readme) is what you want to use - I do this often [in my projects](https://github.com/G-Rath/audit-app/blob/main/test/setupMockFs.ts).
