### ISSUE TITLE
Unsorted Filenames

### ISSUE THREAD

**Issue by wandersonwhcr** [streamich/memfs#37]
Hello!

First, thank you for your package. I am a Node.js beginner and `memfs` helps me a lot with testing and mocking.

I am developing a package to load configuration alphabetically by filenames. Searching for Node.js `fs` `readdir` behavior, I just realize this method is always sorted on Linux, but not on Windows (or filesystems, whatever).

https://github.com/nodejs/node/issues/3232

https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback
http://man7.org/linux/man-pages/man3/readdir.3.html#NOTES

Thinking about it, currently, I can't simulate a `readdir` with unsorted filenames in `memfs`.

https://github.com/streamich/memfs/blob/master/src/volume.ts#L1486

Can we improve some configuration to disable that feature, or implement another sort?

**Comment by wandersonwhcr** [comment]
Related with wandersonwhcr/node-config#25

**Comment by streamich** [comment]
Well, in general the file names are not guaranteed to be sorted, as [`readdir(3)` states](http://man7.org/linux/man-pages/man3/readdir.3.html#NOTES):

> The order in which filenames are read by successive calls to readdir() depends on the filesystem implementation;

I added sorting to `readdir` function because Node's `fs.readdir` would return files sorted on my Ubuntu machine, I guess that was a mistake.

From nodejs/node#3232 I see that Linux users will expect the files to be sorted. So, I will add a check for Windows:

```js
if(!isWind && encoding !== 'buffer') list.sort();
```

**Comment by wandersonwhcr** [comment]
But if I want to simulate Windows runtime in my tests, how can I do that?

I don't know if `memfs` must do this, but it will improve tests on dependent packages.

**Comment by streamich** [comment]
> But if I want to simulate Windows runtime in my tests, how can I do that?

```js
process.platform = 'win32';
```

**Comment by streamich** [comment]
Published under version `2.5.4`

**Comment by wandersonwhcr** [comment]
Thanks for your attention, but I think it's wrong to modify a global element like `process` to run a test. I'll try my own way. Again, thank you :+1:

**Comment by streamich** [comment]
@wandersonwhcr how would you suggest to do it?

**Comment by wandersonwhcr** [comment]
I'll create a PR soon
