### ISSUE TITLE
Better support for older Node.js versions

### ISSUE THREAD

**Issue by rangoo94** [streamich/memfs#419]
Hello,

I came to issue that right now `memfs` is not working on older Node.js version than 5.10, while it can be easily fixed.

* `Buffer.from` and `Buffer.allocUnsafe` - these methods have been [added](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array) in Node.js 5.10
  * [`buffer-from`](https://www.npmjs.com/package/buffer-from) and [`buffer-alloc-unsafe`](https://www.npmjs.com/package/buffer-alloc-unsafe) ponyfills can be used

**Comment by streamich** [comment]
Thanks, I like the idea of supporting older versions of `Buffer`, but it somehow feels that adding two extra dependencies for everyone for something like this is too much.

Maybe users should polyfill this themselves? Or we can polyfill this with one line, like this:

```js
if (!Buffer.from) Buffer.from = Buffer.allocUnsafe = (...args) => new Buffer(...args);
```
