### ISSUE TITLE
`fs.promises` incompatibility with Node.js FS

### ISSUE THREAD

**Issue by rangoo94** [streamich/memfs#420]
Hello,

If someone would like to use `memfs` as `fs` replacement, there is `promises` incompatibility issue:

* `'promises' in fs`
  * In native `fs` (`node >= 10`) it will result in `true`
  * In native `fs` (`node < 10`) it will result in `false`
  * In `memfs` (any Node.js version) it will result in `true`
* `fs.promises`
  * In native `fs` (`node >= 10`) it will result in object with promisified FS API
  * In native `fs` (`node < 10`) it will result in `undefined`
  * In `memfs` (`node >= 0.11`) it will result in object with promisified FS API
  * In `memfs` (`node < 0.11`) it will **throw error**

It means, that either:

* `memfs` should not expose `promises` in `node < 0.11` (when `Promise` is not available)
* `memfs` should not expose `promises` in `node < 10`
* `memfs` should have an optional parameter `strictCompatibility: boolean` to decide if it should set up `promises` API

In my opinion the first option seems to be the best - it will allow using `promises` API before Node 10, but feature detection will work correctly as well. `strictCompatibility` could be added in that case, but it will be needed very rarely (only when someone will use `'promises' in fs` to check if it's Node >= 10.

What do you think about that?

**Comment by streamich** [comment]
The goal of `memfs` is to support the latest `fs` API of Node. But `memfs` does not have to be run in Node environment at all, it can be run in the browser, or wherever one wants. Thus, detecting Node version does not seem to fit into the scope of this package, if someone needs to match `memfs` behaviour to native Node's `fs` to this level of granularity, maybe it could be a separate package that internally uses `memfs` and shapes it according to Node's version.

**Comment by Seb35** [comment]
Personally I’m quite convinced by the explanation saying that memfs’ promises API is decorrelated from node’s version and I find this issue could be closed.

Also the file [docs/dependencies.md](https://github.com/streamich/memfs/blob/master/docs/dependencies.md) is quite clear about when the promises API is available in memfs, and checking if promises API is available in some JavaScript program could be achieved like in memfs with `typeof Promise === "undefined"`.
