### ISSUE TITLE
Don't use fs-monkey internal API

### ISSUE THREAD

**Issue by dawidgarus** [streamich/memfs#441]
memfs uses fs-monkey internal API:
```javascript
const { fsSyncMethods, fsAsyncMethods } = require('fs-monkey/lib/util/lists');
const { unixify } = require('fs-monkey/lib/correctPath');
```
which is not documented and could be changed without warning at any time.
memfs requires fs-monkey with version ^0.3.3 and it work fine with latest 0.3.3 version, but what if they decided to do some refactoring and move the modules required by memfs?
The least you could do is to change the dependency version to be exactly 0.3.3, because right now it's risky to use memfs in any project, as it could stop working after dependency update or fresh installation.

**Comment by G-Rath** [comment]
I'm going to close this issue as I don't think it's much of a concern: `fs-monkey` is authored by the same person who authored `memfs`, so any refactoring pain would be self inflicted :)

I have opened up a [PR](https://github.com/streamich/fs-monkey/pull/190) to export some things on the top level, but I think the way it's being used is fine :)

Cheers for bring it up however - it's good to have this sort of thing discussed!
