### ISSUE TITLE
No code in release 2.16.0

### ISSUE THREAD

**Issue by Elrendio** [streamich/memfs#447]
No code was published to NPM in version 2.16.0 (missing folder src) therefore all packages depending on this one are broken :( 

Probably related to #426

**Comment by EricCrosson** [comment]
I am seeing this also, the `lib` folder is not present in `node_modules/memfs` after a clean `npm instal memfs`

**Comment by prokopsimek** [comment]
@streamich Please fix that issue. 🛠https://github.com/streamich/memfs/issues/426

**Comment by aatwo** [comment]
encountered this issue yesterday

**Comment by streamich** [comment]
Sorry, please download `2.16.1`.

**Comment by aatwo** [comment]
Thanks for fixing the issue. No need to be sorry. It happens :)

**Comment by prokopsimek** [comment]
@streamich Thanks a lot! :) Good job! 🛠
