### ISSUE TITLE
Patch fs for a specific path for use in testing

### ISSUE THREAD

**Issue by vjpr** [streamich/memfs#47]
When I use `patchfs` in `fs-monkey`, requires break.

I want to patch `fs` so that I can run some tests which use `fs` and `fs-extra`...but I still need to be able to require.

---

Maybe I should use `patchFs` with the `unionfs` filesystem of `memfs` and native `fs`?

**Comment by streamich** [comment]
If you are using `jest`, take a look at

1. [`jest-plugin-fs`](https://www.npmjs.com/package/jest-plugin-fs)
2. or https://github.com/sapegin/mrm-core/blob/master/__mocks__/fs.js

I am not sure why `require` breaks if you use `patchFs`, can you please paste your code snippet where you use `patchFs`?
