### ISSUE TITLE
How to create a dir with `fromJSON` without using a temp file?

### ISSUE THREAD

**Issue by vjpr** [streamich/memfs#48]
[`mock-fs`](https://github.com/tschaub/mock-fs#example) supports a nested structure and represents empty dirs as empty objects.

At present I am using the `flat` module to take a nested structure into `fromJSON`, but there seems no way to create dirs without dummy files.

**Comment by streamich** [comment]
> but there seems no way to create dirs without dummy files.

Yes, currently there is no way to specify an empty directory from the JSON.

Specifying an empty dir as an object sounds interesting though, I might add it in the future, or accept a pull request.

We had already a similar discussion: https://github.com/streamich/memfs/issues/29#issuecomment-325956023

The JSON could be even more generic, accepting also permissions, symlinks and hard links.

**Comment by vjpr** [comment]
> The JSON could be even more generic, accepting also permissions, symlinks and hard links.

This would be really cool. 

Maybe it could even be a separate module...because it seems like it would be useful outside of `memfs` too.

**Comment by streamich** [comment]
> Maybe it could even be a separate module...because it seems like it would be useful outside of memfs too.

How would it be useful?

**Comment by vjpr** [comment]
Well it is just calls to `fs.writeFileSync`, so it doesn't actually depend on `memfs`.

If I want to write a dir structure to disk, I could just pass the regular `fs` to it. Making it easy to go back and forth between `memfs` and regular files if necessary.

Might also be useful to allow writing a `memfs` volume to disk for easy navigation with Finder.

```js
const jsonToFs = require(`json-to-fs`)
const json = vol.toJSON()
jsonToFs(json, fs)
```

**Comment by vjpr** [comment]
Just leaving this workaround here...

```js
import flatten from 'flat'
const keep = {'.keep': ''}
const files = flatten({
  '/mono-idea-project': {
    foo: {
      bar: {node_modules: keep},
    },
  },
})
```

**Comment by streamich** [comment]
Can be done now using `{}` object literal:

- https://github.com/streamich/memfs/issues/106

**Comment by alex996** [comment]
> Can be done now using `{}` object literal:
> 
> * #106

@streamich Is this still the case? If so, we may want to update TS definitions:

```ts
const fs = Volume.fromJSON({ '/some-dir': {} });
```

```
Type '{}' is not assignable to type 'DirectoryContent'.
```

`Volume.fromJSON({ '/some-dir': null });` works fine though.

**Comment by G-Rath** [comment]
@alex996 while it would technically work, I think the types should remain as requiring `null` because using `{}` naturally leads to assuming `{ '/some-dir': { '/some-nested-dir': {} } }` would work, which it doesn't (for that you need to call `fromNestedJSON`), and because `{}` in TS actually means an open object, so it makes it a bit of a footgun & technically a breaking change if we wanted to say merge `fromJSON` & `fromNestedJSON`.

**Comment by alex996** [comment]
@G-Rath Thanks, using `null` then.
