### ISSUE TITLE
Problems using in browser

### ISSUE THREAD

**Issue by talbet** [streamich/memfs#49]
I have tried to test this in the browser by cloning the example webpack repo linked in the readme. Unfortunately when I run it I encounter the following error `Uncaught TypeError: Cannot read property 'sep' of undefined`.

It looks like memfs has a dependency on path, or a path-like library that prevents it from being used in the browser. Are you aware of any modules that can be used to fix this?

**Comment by streamich** [comment]
Fixed it:

https://github.com/streamich/memfs/pull/50

Published new version `memfs@2.5.8`.

**Comment by talbet** [comment]
Thanks for the quick response, it's working again now 👌
