### ISSUE TITLE
volume-localstorage is not persistent?

### ISSUE THREAD

**Issue by nwtgck** [streamich/memfs#509]
Hi!

I'd like to persistent a filesystem into localStorage, but it seems to be not persistent.

Here is my simple code using `createVolume()` in volume-localstorage.

```ts
import {createVolume} from 'memfs/lib/volume-localstorage';
const Volume = createVolume('mynamespace');
const vol = new Volume();

console.log('json1:' ,vol.toJSON());
// => {}
vol.writeFileSync("/hello.txt", "hello, world");
console.log('json2:' ,vol.toJSON());
// => {/hello.txt: "hello, world"}
```
## console
<img width="324" alt="image" src="https://user-images.githubusercontent.com/10933561/74854595-e6210900-5382-11ea-82d6-4f8e23812192.png">

The "json1" is always "{}" after reloading. I expect the  "json1" is `{/hello.txt: "hello, world"}` after reloading.

Could you tell me whether my use is correct or not?

**Comment by streamich** [comment]
The `volume-localstorage` project was never finished, there is a lot to be done to make it work.

**Comment by nwtgck** [comment]
@streamich Thanks for the reply.
