### ISSUE TITLE
Paths broken on Windows (after upgrade from 2.5.7 to 2.5.8)

### ISSUE THREAD

**Issue by dominique-mueller** [streamich/memfs#51]
After upgrading to the latest version (`2.5.8`), reading directories (in my case by using `readdir`) does no longer work properly.

I did a bit of debugging, and found out that the path separator is wrong (`\` instead of `/`) which leads to paths not getting split correctly (they don't get split into `steps` at all, to be particular). A few hours later I discovered this PR (https://github.com/streamich/memfs/pull/50) which got merged a few days ago. Before this PR (version `2.5.7`) everything works as expected, the latest version including the PR (version `2.5.8`) does no longer.

Seems to me that, in order to get the correct separator, we check whether posix exists on the `path` module (see https://github.com/streamich/memfs/blob/master/src/volume.ts#L21), but we still use the separator from the normal `path` module instead of `path.posix` (which contains the correct separator).

I'm don't have that much experience with NodeJS tooling, but might it be possible that there is some bug here?

**Comment by streamich** [comment]
Thanks, for bringing this up.

It must be a silly mistake by me #52, please try version `2.5.9`.

**Comment by dominique-mueller** [comment]
Awesome, I can verify that everything is working again! Thanks for the quick fix! 👍
