### ISSUE TITLE
Read existing disc files to memory?

### ISSUE THREAD

**Issue by gitcatrat** [streamich/memfs#522]
This is not supported? I can't find anything about it in docs nor anywhere else. 
Could I get pointers how to do this?

Use case: I want to use in-memory filesystem to speed up Webpack build times.

Example file structure:
```js
project
  - my_modules
  - node_modules
  - server
      - server.js (here be memfs)
```
I basically need to create a memory filesystem that has all the directories and files in `project`.

I'm sorry about the question in issue tracker.

**Comment by G-Rath** [comment]
You can do this using [unionfs](https://github.com/streamich/unionfs) :)

**Comment by G-Rath** [comment]
Here's how I do it in one of my [projects](https://github.com/G-Rath/terra/blob/master/test/setupMockFs.ts).

**Comment by gitcatrat** [comment]
@G-Rath  Thank you for quick response!  Then I misunderstood `unionfs`, I got the impression that it only enables to use both in-memory and disc filesystems with same API but doesn't actually write the disc filesystem into memory. Was I wrong?

**Comment by G-Rath** [comment]
`unionfs` will attempt fs actions on each of the file systems its been given, until one succeeds.

So the flow ends up going something like this:

1. read file from disk
  * memfs: error, file does not exist!
  * real fs: file exists -> serves data, unionfs returns the result
2. do stuff with data
3. write back to file
  * memfs: writes successful -> unionfs stops here

This means that the file will be "copied" to the memfs when it's written.

It sounds like what you want is a method to mirror the existing filesystem into memfs, which isn't really within the scope of memfs as you can achieve this by just recursively reading & writing in the fs which you could do easily with something like [`recursive-copy`](https://github.com/timkendrick/recursive-copy) :)

**Comment by gitcatrat** [comment]
@G-Rath Could you give me few pointers? `recursive-copy` only takes destination as string.
