### ISSUE TITLE
Callback was already called.

### ISSUE THREAD

**Issue by mariusrak** [streamich/memfs#542]
Hi, I'm using memfs with webpack and its watcher. After rebuild I want to read a file that was just built, but get this error:

```Uncaught exception:  Error: Callback was already called.
    at throwError (C:\...\node_modules\neo-async\async.js:16:11)
    at C:\...\node_modules\neo-async\async.js:2818:7
    at C:\...\node_modules\neo-async\async.js:2830:7
    at done (C:\...\node_modules\neo-async\async.js:3517:9)
    at C:\...\node_modules\webpack\lib\Compiler.js:548:25
    at Immediate.<anonymous> (C:\...\node_modules\memfs\lib\volume.js:684:17)
    at processImmediate (internal/timers.js:456:21)```

**Comment by G-Rath** [comment]
Could you provide some more information about your setup and how you're trying to do what you're trying to do? (A reproduction repo would ideal, but otherwise some code would also be useful)

Assuming you're using the latest version of memfs, `memfs\lib\volume.js:684:17` holds `var node = child.getNode();` in `_toJSON`, meaning something is asking memfs to render the state of itself in JSON form and it's erroring for some reason.

**Comment by mariusrak** [comment]
Here's the important part of my code. But I found out, that I have some other error, which comes up on webpack rebuild. And it seems that while there's no error in memfs, it blocks displaying actual user-code error.  So the issue here would be, why memfs is hiding the error.

```javascript
const path = require("path");
const watchpack = require("watchpack");

const { createFsFromVolume, Volume } = require("memfs");
const fs = createFsFromVolume(new Volume());

const webpack = require("webpack");

const compiler = webpack([
        {
                entry: path.resolve(__dirname, "./file.js"),
                output: { path: path.resolve(__dirname, "dist"), filename: "file.js" },
                mode: "development",
        },
]);
compiler.outputFileSystem = fs;
const WatchHandler = compiler.watch(
        {
                aggregateTimeout: 300,
                poll: undefined,
        },
        (err, stats) => {
                if (err) {
                        console.log(err);
                } else if (stats.hasErrors()) {
                        console.log(stats.toString({ colors: true }));
                } else {
                        // I have error here
                }
        }
);
```

**Comment by G-Rath** [comment]
@mariusrak would you be able to put together a repo reproducing this behaviour that I could use to better investigate?

**Comment by bpatath** [comment]
I got this issue too. It comes from an error in the `Volume.wrapAsync` method. Currently, the try block contains both calls to `method` and `callback`. Thus, if it is the callback which raises an exception, the callback will be called a second time in the `catch` block and the `Callback was already called.` will happen.

Calling the callback should be a separated step ensuring that the callback is only called once, e.g.:
```javascript
let v = null, e = null;
try {
  v = method.apply(...);
} catch (err) {
  e = err;
}
callback(e, v);
```

For some context, I also encountered this error while using memfs as a webpack output filesystem. I was trying to read the output file using `fs.readFileSync` but using the wrong path.  
With the current version, I can't catch the exception and node crashes with `Callback was already called`.
With the patch above, I can catch the expression which contains `ENOENT: no such file or directory, open 'myfile.js'`.

**Comment by G-Rath** [comment]
@bpatath @mariusrak would either of you be able to provide a sample repo reproducing this problem so that I can investigate?

I'm happy to look into this, but have a heavy workload atm that means I don't really have the bandwidth to invest into figuring out the setup needed to reproduce - having a repo that I can just `npm install && npm run do-the-thing` would make it much easier for me to action :)

(it doesn't have to be just one command, - having a repo with all the right code & configs, + the steps to create the error is the main thing)

**Comment by AvalonCV** [comment]
Hello everyone,

sorry if I jump into this, but I recently encountered the same error. @G-Rath I uploaded my _broken_ code to https://github.com/AvalonCV/p2020 . npm install && npm run dev-server should lead you to the problem (that I was able to fix using the changes proposed by @bpatath to find the actual error).

Best regards

**Comment by G-Rath** [comment]
Ah, I think I see what's happenings - the `callback` itself is throwing an error, that must happen after the `callback` internally registers itself as called.

That's a good catch - I'll try and have a PR up tonight fixing it :)

**Comment by AvalonCV** [comment]
Great. Thank you very much :)

**Comment by privatenumber** [comment]
Hope it's alright if I work on a fix for this
