### ISSUE TITLE
fs.open fails on directory

### ISSUE THREAD

**Issue by kirilknysh** [streamich/memfs#58]
**memfs version**: 2.6.0
**OS version**: macOS High Sierra 10.13.2 (17C88)

`fs.open` with read flag fails on directory. Though Nodejs' `fs` module allows to "open" folder.

A short code snippet to reproduce the issue:
```
const fs = require('fs');
const path = require('path');

const memfs = require('memfs');

const vol = new memfs.Volume();
const dir = path.resolve(process.cwd(), 'open-test');
vol.mkdirpSync(dir);
const fsmem = memfs.createFsFromVolume(vol);

fs.open(dir, 'r', (err, fd) => {
    console.log('fs', err);
});

fsmem.open(dir, 'r', (err, fd) => {
    console.log('memfs', err);
});
```

produces the output:
```
fs null
memfs { Error: EISDIR: illegal operation on a directory, open '/Users/kirilknysh/Projects/memfs-open/open-test'
    at createError (/Users/kirilknysh/Projects/memfs-open/node_modules/memfs/lib/volume.js:105:17)
    at throwError (/Users/kirilknysh/Projects/memfs-open/node_modules/memfs/lib/volume.js:114:11)
    at Volume.openLink (/Users/kirilknysh/Projects/memfs-open/node_modules/memfs/lib/volume.js:716:13)
    at Volume.openFile (/Users/kirilknysh/Projects/memfs-open/node_modules/memfs/lib/volume.js:748:25)
    at Volume.openBase (/Users/kirilknysh/Projects/memfs-open/node_modules/memfs/lib/volume.js:752:25)
    at Immediate.<anonymous> (/Users/kirilknysh/Projects/memfs-open/node_modules/memfs/lib/volume.js:623:39)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) code: 'EISDIR' }
```

Why to open directory? Sometimes, to ensure that a new file is created and exists in directory listing - `fsync` on parent directory must be called. Some details could be found https://www.quora.com/When-should-you-fsync-the-containing-directory-in-addition-to-the-file-itself .

**Comment by streamich** [comment]
It should probably emulate [Node.js behaviour](https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback):

>Note: The behavior of fs.open() is platform-specific for some flags. As such, opening a directory on macOS and Linux with the 'a+' flag - see example below - will return an error. In contrast, on Windows and FreeBSD, a file descriptor will be returned.

```js
// macOS and Linux
fs.open('<directory>', 'a+', (err, fd) => {
  // => [Error: EISDIR: illegal operation on a directory, open <directory>]
});

// Windows and FreeBSD
fs.open('<directory>', 'a+', (err, fd) => {
  // => null, <fd>
});
```

**Comment by kirilknysh** [comment]
For `a+` flag - yes, and this is correct. But for `r` flag - the behaviour is different.

**Comment by kirilknysh** [comment]
Also, the [open(2)](http://man7.org/linux/man-pages/man2/open.2.html) docs say:

![image](https://user-images.githubusercontent.com/3236551/34610537-e8fcbe22-f221-11e7-9a5c-d8dc8fa46b22.png)

**Comment by kirilknysh** [comment]
Please, take a look at https://github.com/streamich/memfs/pull/59

**Comment by streamich** [comment]
Looks good, thx, I've merged it.

**Comment by streamich** [comment]
It has been released here:

https://github.com/streamich/memfs/releases/tag/v2.6.1

**Comment by kirilknysh** [comment]
Thanks!
