### ISSUE TITLE
How to run two seperate script. One of them requires another file created with memfs?

### ISSUE THREAD

**Issue by bunyaminmrcn** [streamich/memfs#611]
Here is the gist. Please help.

[https://gist.github.com/bunyaminmrcn/68fffb3110869a649f4abcce018442ab](https://gist.github.com/bunyaminmrcn/68fffb3110869a649f4abcce018442ab)

**Comment by G-Rath** [comment]
Questions tend to be better put on forms or stackoverflow, as issues are meant more for reporting bugs or requesting features.

Looking at your gist I'm not sure what you're trying to do or how you're going about it so can't provide any more help without more details, except to say that if you're meaning you're running two apps separately you'll not be able to share the memfs instance as the two apps run as their own separate processes
