### ISSUE TITLE
how to sync volume to real file system

### ISSUE THREAD

**Issue by bung87** [streamich/memfs#613]
I use this lib before but only write file to disk one by one, I wonder to know how to sync volume to real file system?
I planed to construct all files and dirs in memory then sync these to real file system.

**Comment by G-Rath** [comment]
If I understand what you're wanting to do correctly, you'd do this by recursively navigating the in-memory file system.

You can do this either "natively" by using `readdir` to get the contents of each directory (starting at the root), and copying as you go, or use `vol.toJSON` to get a copy of the whole in-memory file-system complete with contents, and then navigate the resulting object.

**Comment by bung87** [comment]
Thanks! really helpfull, I think I can simply use `vol.toJSON`
