### ISSUE TITLE
"toJSON" can't support binary file 

### ISSUE THREAD

**Issue by LongOddCode** [streamich/memfs#624]
hi, the signature of DirectoryContent is `declare type DirectoryContent = string | null`. 

But as a filesystem, I should write binary data to a file like 
``` javascript
http.request(url, function (response) {
    var data = new Stream();

    response.on('data', function (chunk) {
        data.push(chunk);
    });

    response.on('end', function () {
        vol.writeFileSync('image.png', data.read());
        vol.toJSON();
    });
}).end();
```

**Comment by G-Rath** [comment]
That's correct - `toJSON` gives you a *JSON* representation of the file system.

**Comment by LongOddCode** [comment]
According to  [issue](https://github.com/streamich/memfs/issues/613), it's recommanded to use toJson to sync to  disk filesystem. So there'll be something wrong if there's a binary file.

**Comment by LongOddCode** [comment]
actually, I jsut want to sync in-memory file to disk, include text & binary files. How to do that gracefully?

**Comment by G-Rath** [comment]
It's *recommended* - that doesn't mean it'll fit every use-case, depending on what you're doing. *all* are binary, and binary can be represented as a string; it all depends on how you parse it.

> I jsut want to sync in-memory file to disk, include text & binary files. How to do that gracefully?

There's a lot of npm packages out there that can help you with this - [`recursive-copy`](https://www.npmjs.com/package/recursive-copy) looks like a good one.
