### ISSUE TITLE
Document Volume.fds and other stuff in `docs/*.md`?

### ISSUE THREAD

**Issue by Artoria2e5** [streamich/memfs#668]
Coming from wasmerio/wasmer-js#263, I am trying to find a way to tell users of `@wasmer/wasmfs` what they can expect in the exported `volume: Volume` property, with the goal of explaining what hooking `wasmerFs.volume.fds[1].write` does and why it's useful.

The issue is that there's no rendered HTML documentation of the `fds` property: `docs/reference.md` does not mention it. My questions are:

* Is `fds` supposed to be public? It is described in the source comments, but linking to source code for docs is a pretty bad idea since you don't get good anchors.
* What is `docs/reference.md` really for? It's pretty spotty for a documentation (notably with `mkdirpSync` referring to an undocumented `mkdirSync`), and appears poorly maintained. Maybe a documentation generator will help?

**Comment by streamich** [comment]
- `fds` is just a list of released file descriptors which will be reused in the future.
- `mkdirp` will be removed in v4.

You might be interested in new File System Access API in v4, it allows to write to real files in browser. See https://github.com/streamich/memfs/tree/next branch
