### ISSUE TITLE
Possible to get data out the same way you put it in?

### ISSUE THREAD

**Issue by megamindbrian** [streamich/memfs#8]
Using:
mem.mount(path, data);
with data like:
```
data = {
    'file.txt': 'Some text',
    'dir/another.txt': 'Other tet'
}
```

Can I get all the data from mem in this same format or do I have to readdir and readfile?

**Comment by streamich** [comment]
Try something like this:

```js
mem.layers[0].files
```

**Comment by megamindbrian** [comment]
Perfect, thank you! Might be worth adding to the instructions, I will PR if
you want?


On Jul 16, 2017 10:55 AM, "streamich" <notifications@github.com> wrote:

Try something like this:

mem.layers[0].files

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/streamich/memfs/issues/8#issuecomment-315625501>, or mute
the thread

**Comment by streamich** [comment]
Sure

**Comment by streamich** [comment]
@megamindbrian with the new version now you have to use `.toJSON` method.

```js
vol.toJSON();
```

**Comment by megamindbrian** [comment]
Even better!
