### ISSUE TITLE
fs.stat callback called two times

### ISSUE THREAD

**Issue by vankop** [streamich/memfs#814]
for case
```js
const { Volume } = require("memfs");
const fs = Volume.fromJSON(
  {
    "/a/foo/a": "",
    "/a/foo/b": "",
    "/a/foo-2/b": "",
    "/a/foo-2/c": "",
    "/b/foo/a": "",
    "/c/foo/a": "",
    "/c/foo/package.json": JSON.stringify({
      browser: {
        "./a": false,
      },
    }),
  },
  "/"
);
let calls = 0;
fs.stat("/c/foo/a", (err, result) => {
  calls++; // in some circumstances this callback called 2 times
});

```
`fs.stat` callback called 2 times, probably because on first call callback throws error

**Comment by NotWearingPants** [comment]
Does not reproduce anymore (and also not on the latest version when this was posted, which was v3.4.1).

According to the code, the callback can't be called twice:

https://github.com/streamich/memfs/blob/3189bf7db1328e84ce305f1463db1472f09f0db3/src/volume.ts#L519-L531

**Comment by G-Rath** [comment]
@NotWearingPants thanks for letting us know!
