### ISSUE TITLE
Cannot find module './getBigInt'

### ISSUE THREAD

**Issue by mrobit** [streamich/memfs#837]
Apologies if this has been answered before or I'm just not understanding it, but `memfs@^3.4.1` as a peer dependency of `webpack-dev-middleware` has an issue where the lib/Stats.js fails to import `./getBigInt` – looking through `node_modules/memfs` the getBigInt.js file is located at `lib/src/getBigInt.js` instead of `lib/getBigInt.js`

Again, sorry if this has been addressed before or I'm not doing it right. Just wanted to see if this has been patched somewhere and I'm a little confused. For now I've reverted to 3.4.1 in my project's `package-lock.json` so we're alright for now, but wanted to post this issue in here in case it was at all helpful. Thanks!

**Comment by JakariaBlaine** [comment]
I got the same issue a couple of minutes ago.

**Comment by patrickconroy** [comment]
I just ran into this as well, tracked it down to this version.

**Comment by mrobit** [comment]
Didn't realize that 3.4.2 just got release 33 min ago 😂 glad to see it's not just me.

**Comment by G-Rath** [comment]
I'll try and look into this now but can't give an ETA sorry - it might have to wait until at least the weekend

**Comment by conlanpatrek** [comment]
If it's helpful, the last version's npm package is borked. Looks like somehow getBigInt.js is winding up in `lib/src/getBigInt.js` but the import path ends up looking in `lib/getBigInt.js`. It's only happening with that one file, the rest of the files end up in `lib` just fine.

**Comment by G-Rath** [comment]
It's because of #818, as `cpy` is what is used to copy `getBigInt.js` into `lib` - currently trying to figure out what actually has changed to cause this as nothing from the release notes (that I've tried) jump out as being the actual cause.

**Comment by kelyar** [comment]
thanks for quick fix
