### ISSUE TITLE
how to make the file system available for a bundler and other javascript modules?

### ISSUE THREAD

**Issue by arunkumar413** [streamich/memfs#843]
I created a file system like below. How to make this file system available for other javascript modules to access?

Say for example, I'd like to make this file system available for rollup as a module so that it can build

`import { rollup } from 'rollup';`

```
  const json = {
    './README.md': '1',
    './src/index.js': '2',
    './node_modules/debug/index.js': '3',
  };

  vol.fromJSON(json, '/app');
  fs.readFileSync('/app/README.md', 'utf8'); // 1

```

**Comment by G-Rath** [comment]
This feels like a pretty broad question as it depends on a lot factors, including the builder and I'd expect it to break as soon as you had a section that required shelling out to an external command (as they'll never be able to see the virtual filesystem).

Generally you want to look at mocking the `fs` module, which can be done in a number of ways (and again depends on what you're using - if t's CJS then you can just modify the `require` cache, but if its ESM then you'll need to use the experimental loader API probably).

**Comment by arunkumar413** [comment]
Yes, the idea is to have a similar functionality like the `fs` module that webpack accepts as the file system to build the app.

I was also thinking that a js tree data structure (https://github.com/shunjizhan/react-folder-tree) that webpack can accept to parse and build the app would also serve the purpose.
