### ISSUE TITLE
Move off CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by G-Rath** [streamich/memfs#868]
I am suspect that the CircleCI integration is broken, since there are no runs for #866 and #867 - this would mean we can't release new versions as @streamich is the only person that has access to the package on npm.

I'm actually going to migrate us to GitHub Actions, but will need the `NPM_TOKEN` setup so that we can resume releases.

@streamich could you set that up, or otherwise give me publishing rights to the packages on npm and admin permissions on the repo to be able to set secrets?

**Comment by G-Rath** [comment]
@williamstein I've setup the GHA workflows so if you would mind rebasing your PRs, we can see if they're passing.

I'm hoping that the release flow is actually still working and that it's just CircleCI being broken somewhere - still I've reached out to @streamich via alternative channels to try and get us unblocked all the same. In the meantime I think we can still work on your PRs and even merge them.

btw ❤️ the work you're putting in - I'm happy to review as many PRs as you're willing to submit, and also do some PRing myself; I've just not had the bandwidth to respond to every reported issue...

**Comment by williamstein** [comment]
Nice regarding GHA workflows!   I did rebase them and they appear to be passing now.

> btw ❤️ the work you're putting in

Thanks!  It's just a key step for using memfs to better support WebAssembly (emscripten, which a lot of people use, has something similar to memfs built in; however, I'm not using emscripten). For WebAssembly all these Sync methods working correctly is very important.

**Comment by G-Rath** [comment]
ok cool it looks like I was correct - CircleCI is still working, it's just the UI connection that's broken: https://github.com/streamich/memfs/pull/875#issuecomment-1294429248

@williamstein can you push up your rebasing, and then we can get your PRs landed.

**Comment by williamstein** [comment]
> @williamstein can you push up your rebasing

Sorry, I'm being really dumb.  What further rebasing, etc. do I need to do?

**Comment by G-Rath** [comment]
You've not pushed up the rebasing - currently the new GHA jobs are not running because they don't actually exist on your remote branch; I can do this if you'd prefer :)

**Comment by williamstein** [comment]
Thanks for the patient clarification!  I've now sync'd my 3 PR's.

**Comment by streamich** [comment]
We are now on GitHub Actions. (I thought that `NPM_TOKEN` and `GH_TOKEN` were setup, but they were set as "Environment Secrets" instead of "Repository Secretes", fixed last week.)
