### ISSUE TITLE
.rm/.rmSync are not available

### ISSUE THREAD

**Issue by alienzhou** [streamich/memfs#884]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/9822789/202646164-fd25cd2c-8a28-4027-b898-d6dbb0524a20.png">

It seems that memfs has implemented `.rm` and `.rmSync`:

https://github.com/streamich/memfs/blob/ce45b54317dcd38b7337ba1977aa74d836ae1d6d/src/volume.ts#L2044-L2053

But memfs uses [fs-monkey](https://github.com/streamich/fs-monkey) to bind methods:

https://github.com/streamich/memfs/blob/ce45b54317dcd38b7337ba1977aa74d836ae1d6d/src/index.ts#L39-L40

`.rm` and `.rmSync` are not supported in the `fs-monkey`'s latest version yet: https://github.com/streamich/fs-monkey/pull/362

Maybe updating this dependency will fix it.

**Comment by blimmer** [comment]
It looks like they just released fs-monkey@1.0.4 last week (https://github.com/streamich/fs-monkey/releases/tag/v1.0.4), which is supported in the `memfs` dependency definition: https://github.com/streamich/memfs/blob/09eab278ec0deb82dd4576dea27a48930e4c0e9b/package.json#L78-L80

I updated my transitive dependencies to grab the newer fs-monkey version and `rmSync` works now.

I also proposed https://github.com/streamich/memfs/pull/909 to specify `1.0.4` as the minimum.
