### ISSUE TITLE
using memfs with webpack

### ISSUE THREAD

**Issue by arunkumar413** [streamich/memfs#886]
Hi Team,

It is possible to use a custom file system with webpack as mentioned in this ( https://webpack.js.org/api/node/#custom-file-systems ) doc. However the doc uses `require` statements. Could you please share us more details on how to use the `import` memfs statements with webpack's `inputFileSystem` and `outputFileSystem` parameters. 

Thanks,
Arun

**Comment by G-Rath** [comment]
I think this question is better asked of the webpack team, since it's their documentation and configuration - memfs should be compatible with `import`, so beyond that it all depends on webpack.

(I've not used webpack a lot lately so don't know what their `import` support is like right now)
