### ISSUE TITLE
fs watch problem

### ISSUE THREAD

**Issue by rutexd** [streamich/memfs#936]
```js
        // ... some other code here. this.fs has "Volume" type (via Volume.fromJson({...});
        const Watcher = this.fs.FSWatcher;

        const watcher = new Watcher();
        watcher.on("delete", (path: string) => {
            // ... my code here
        });
        watcher.start("/", false, true);
        
       // ...
```
Example of my fs: 
```
- FolderA
-     file1.txt, file2.txt, 3...
- FolderB (empty)
```
after then, trying to rename folder with ``fs.renameSync`` produces weird error. ``fs.renameSync("/FolderB", "/FolderBBB")`` and so on...
``this.fs.watch("/", ...)`` produces same error
crashes only on renaming existing folders. not files.

Error:

```
Unhandled Rejection at: Promise {
  <rejected> RangeError: Maximum call stack size exceeded
      at C:\dev\proj-memfs\node_modules\memfs\lib\volume.js:1863:25
      at Array.forEach (<anonymous>)
      at removeLinkNodeListeners (C:\dev\proj-memfs\node_modules\memfs\lib\volume.js:1862:53)
      at C:\dev\proj-memfs\node_modules\memfs\lib\volume.js:1864:29
      at Array.forEach (<anonymous>)
      at removeLinkNodeListeners (C:\dev\proj-memfs\node_modules\memfs\lib\volume.js:1862:53)
      at C:\dev\proj-memfs\node_modules\memfs\lib\volume.js:1864:29
      at Array.forEach (<anonymous>)
      at removeLinkNodeListeners (C:\dev\proj-memfs\node_modules\memfs\lib\volume.js:1862:53)
      at C:\dev\proj-memfs\node_modules\memfs\lib\volume.js:1864:29
} 
```

**Comment by G-Rath** [comment]
Would you mind checking against the last few versions of v3? that included a couple of changes relating to the watcher - probably the main versions to check ideally would be v3.6, v3.5, and v3.4

**Comment by rutexd** [comment]
Just downgraded to 3.4. Looks like renaming is working.

**Comment by G-Rath** [comment]
My guess is it's probably https://github.com/streamich/memfs/commit/43e82223046362c5e0176c112675c5636baac389

Would you mind trying to put together a self-contained reproduction script?

**Comment by rutexd** [comment]
```js

const memfs = require("memfs");
const { Volume } = memfs;

function main() {

    const json = {
        "/a/1.txt": "1",
        "/a/2.txt": "2",
        "/b": null,
    }

    const fs = Volume.fromJSON(json);

    fs.watch("/", {recursive: true}, (ev, p)=>{
        console.log(ev, path)
    });

    fs.renameSync("/b", "/bb/");

}


main();
```

tested on NodeJS 18

**Comment by G-Rath** [comment]
Thanks, that works - looks like it was actually https://github.com/streamich/memfs/commit/8af880ed831493f38cedea827396a154a8fbce37 that broke this.

I think we missed a condition: https://github.com/streamich/memfs/commit/8af880ed831493f38cedea827396a154a8fbce37#diff-dde13e8c51a8a2e1bce9d7d5dc9ada7cb503492d5e43ab27b996fb6038dde296R2796-R2798

**Comment by rutexd** [comment]
im afraid, im not able to understand this code fastly :)

is there anything else i can do to help?
