### ISSUE TITLE
Node.js APIs used in browser in fsa-to-fs

### ISSUE THREAD

**Issue by remixer-dec** [streamich/memfs#949]
I'm trying to use [fsa-to-fs](https://github.com/streamich/memfs/blob/master/docs/fsa/fsa-to-fs.md), in a Vue+Vite app in browser, but it crashes trying to use Node APIs such as buffer and process. 

code used:
```
import { FsaNodeFs } from 'memfs/lib/fsa-to-node';
```

errors:
<details><pre>
Uncaught TypeError: buffer_1.Buffer is undefined
    js buffer.ts:7
    __require chunk-CF3WPAMV.js:9
    js encoding.ts:1
    __require chunk-CF3WPAMV.js:9
    js options.ts:3
    __require chunk-CF3WPAMV.js:9
    js FsaNodeFs.ts:1
    __require chunk-CF3WPAMV.js:9
    js index.ts:1
    __require chunk-CF3WPAMV.js:9
    <anonymous> memfs_lib_fsa-to-node.js:5041
</pre></details>

and after trying to fix it wtih `npm install buffer`

<details>
<pre>
Uncaught ReferenceError: process is not defined
    js util.ts:8
    __require chunk-CF3WPAMV.js:9
    js options.ts:5
    __require chunk-CF3WPAMV.js:9
    js FsaNodeFs.ts:1
    __require chunk-CF3WPAMV.js:9
    js index.ts:1
    __require chunk-CF3WPAMV.js:9
    <anonymous> memfs_lib_fsa-to-node.js:6908
[util.ts:8:13](http://127.0.0.1:5173/node_modules/memfs/src/node/util.ts)
</pre>
</details>

after trying to fix it with `npm install process` and manually importing it in [utils](https://github.com/streamich/memfs/blob/master/src/node/util.ts#L8) where it is used as global variable

<details>
<pre>
Uncaught TypeError: class heritage stream_1.Writable is not an object or null
    js FsaNodeWriteStream.ts:32
    __require chunk-CF3WPAMV.js:9
    js FsaNodeFs.ts:14
    __require chunk-CF3WPAMV.js:9
    js index.ts:1
    __require chunk-CF3WPAMV.js:9
    <anonymous> memfs_lib_fsa-to-node.js:7058
</pre>
</details>

**Comment by streamich** [comment]
Hey! You need to make your build system bundle substitutes for those Node modules, here is how it is done in this [Webpack config](https://github.com/streamich/memfs/blob/master/demo/git-fsa/webpack.config.js#L29-L35).

**Comment by remixer-dec** [comment]
Thanks a lot, it works, please mention this requirement somewhere in the docs.
