### ISSUE TITLE
Reconsider use of json-joy dependency

### ISSUE THREAD

**Issue by thatsmydoing** [streamich/memfs#980]
`json-joy` has `quill-delta` and `rxjs` as peer dependencies which aren't really needed for `memfs` to work. Since only the CBOR and JSON encoders are used from the package. Would it be possible to replace it with a more targeted dependency?

**Comment by G-Rath** [comment]
I'd be happy to accept PRs moving us off `json-joy`

**Comment by thatsmydoing** [comment]
I did make a branch for this but realized that the problem here (and with `json-joy`) is that they're doing too much. It seems like this package should be split up into a core `memfs` just for node and separate packages for the experimental FSA adapters (since only those use the extra dependencies).

I realize that's a big ask so I understand if that's out of scope of the project.

**Comment by G-Rath** [comment]
alternatively, we could try to make `json-joy` an optional peer dependency 🤔

**Comment by G-Rath** [comment]
@thatsmydoing I'm just released [v4.8.0-next.1](https://github.com/streamich/memfs/releases/tag/v4.8.0-next.1) which makes both dependencies optional

**Comment by thatsmydoing** [comment]
Oh, sorry just got back to this. Thanks for doing this. Which part of core `memfs` used `json-joy`?

**Comment by G-Rath** [comment]
`src/print/index.ts` iirc
